### ISSUE TITLE
Phus Lu人身安全的讨论

### ISSUE THREAD

**Issue by dou4cc** [goproxy0/goproxy#2]

**Comment by dou4cc** [comment]
这代表什么？
![image](https://user-images.githubusercontent.com/7764678/31045571-5afb993a-a619-11e7-9aef-e928773c6a28.png)

**Comment by Just2co** [comment]
咱昨晚8点多还在跟phuslu交流！今天早上一起来就发现项目不见了。这几天，各个执法单位执法明显严格起来，公安，消防，交警，食药监全线出动，逮住狠罚！就是为了19大维稳。

**Comment by blob2015** [comment]
@Just2co 用的IM还是邮件？还是？

**Comment by Just2co** [comment]
@blob2015 就是我俩现在这种issue交流方式，我跟他汇报IPv6下goproxy的使用情况。今天早上上班看看情况，就发现项目不见了。

**Comment by caofengzi** [comment]
祝社長安好。

**Comment by masktao** [comment]
祝社长一切安好,好人平安

**Comment by hyperdoit** [comment]
等19大过了就好了吧

**Comment by shujunwu** [comment]
祝社长安好

**Comment by dou4cc** [comment]
社长刚刚又活动了，谁能告诉我哪里update了？
![default](https://user-images.githubusercontent.com/7764678/31051847-a9117536-a6a5-11e7-9c35-5a305666c16d.png)

**Comment by dou4cc** [comment]
![default](https://user-images.githubusercontent.com/7764678/31052418-acb7614e-a6b6-11e7-981c-e0a7ea2c6f64.png)

**Comment by carotin** [comment]
但愿社长安好~

**Comment by dou4cc** [comment]
我大概可以确定社长这次是删项目而非转为私有。因为：
- 上次phuslu/goproxy转为私有后，我翻阅@jasonliul和其他经常发issue的人的activities，open的issues一个没少，只是点进去后是404
- 这次404，我的activities和其他人的activities都像被洗过一样，一个phuslu/goproxy的issue都见不到了
- phuslu上次关issues后反复道歉，可见他即使不再开发，也不会舍得删issues

**Comment by xyuanmu** [comment]
我记得不是说已经出国了么，好在现在 goproxy 已经很完善
还是我这种小地方好，只要不杀人放火，基本没人管，最不爽的就是扣摩托车 :rage:

**Comment by dou4cc** [comment]
@xyuanmu phuslu没匿名，一直住在南京。

**Comment by shujunwu** [comment]
@dou4cc 
在github上再也找不到社长的影子，默默的在这里找到了存档，从开始到r1623可惜没有r1624
也许社长会回来的，一个人的心血怎么也舍不得丢下，
![2017-10-02 15 06 24](https://user-images.githubusercontent.com/31476931/31067122-d37e8ff0-a783-11e7-99b9-fb24160875d7.png)
![2017-10-02 14 52 21](https://user-images.githubusercontent.com/31476931/31067123-d392edba-a783-11e7-9ef0-90e07591f62a.png)
这里：
http://goproxy.sourceforge.net/?

**Comment by dou4cc** [comment]
@shujunwu r1624就是更新了个gfwlist.txt，你自己手动替换一下就行。

**Comment by dou4cc** [comment]
@shujunwu 
> 社长会回来的，一个人的心血怎么也舍不得丢下

你还记得clowwindy吗？被喝茶之后就失踪了，跟死了一样。

**Comment by candy2107** [comment]
@dou4cc
这次应该是迫于压力关闭项目,不会继续开发了

**Comment by candy2107** [comment]
@shujunwu
这次应该是迫于压力关闭项目,不会继续开发了

**Comment by shujunwu** [comment]
@dou4cc 
@candy2107
不管社长会不会在开发，只要他平安就好，不知道有多少人在默默地为他着急祈祷！！！

**Comment by dou4cc** [comment]
@shujunwu 连开发软件的自由都没有了，能平安到哪去？

**Comment by SeaHOH** [comment]
所以说，你们不要鼓吹匿名啥的。
社长只是提供一个浏览网络的工具而已，但是被别人附会了各种理由。

**Comment by blob2015** [comment]
@SeaHOH 
或者说各种高帽……

**Comment by fei5seven** [comment]
@dou4cc clowwindy这个人还在偶尔玩玩推特，虽然以前是加密状态，但是他好像是对我解锁的？我能看得到，如图最新是9.22的还在秀生活呢
![qq 20171002233257](https://user-images.githubusercontent.com/12988636/31085542-0c902bc8-a7ca-11e7-8fe2-254aa2613312.jpg)

**Comment by dou4cc** [comment]
@fei5seven 你这不是follow了吗（

**Comment by fei5seven** [comment]
@dou4cc 单纯follow好像不能查看吧？最一开始是提示需要所有者对你进行解锁来着？

**Comment by fei5seven** [comment]
喝茶没事，最不济就是交出源代码放人就是了。毕竟坦白的话也算大功一件？【笑】

**Comment by fuckGFW2015** [comment]
除非你身在墙外，不然此类敏感东西，懂得自我保护（匿名开发）很有必要啊！
