### ISSUE TITLE
GoProxy的未来

### ISSUE THREAD

**Issue by dou4cc** [goproxy0/goproxy#3]
@xxnet @SeaHOH @jasonliul @candy2107 @johnsonz @Kisesy @fei5seven @blob2015 @Asteroids89 @qwerttaa @e2889e @ARwMq9b6 @MeABc @jzmswe @hyperdoit @lizongzeshunshun @Just2co @pgz123 @cxjava @yfdyh000 @jostyee @overajog @codexss @alsotang @renzhn @cyfdecyf @Akkariiin

**Comment by Just2co** [comment]
各位菊苣！未来在我们的手中。

**Comment by blob2015** [comment]
露个脸，先不要想太多，等社长现身、或者消息吧

**Comment by mixool** [comment]
是不是可以搞个组织，然后社长作为成员匿名继续开发。

**Comment by blob2015** [comment]
@mixool 如果是“外力”，估计会要求写个保证什么的了。然后上了某些“观察者”名单——这个名单会下沉到社区、居委会一级，不时会有人找你谈话、要求汇报，同时问邻居你的情况。
找工作都会很麻烦。
但反过来说，也就这样了。又不是什么高价值目标，只是一个维稳分子。
如果真是有事，不是要求社长什么了，而是希望他个人生活无碍，家庭不受惊吓。
当然，现在这都是瞎想，等有消息了再说吧。

**Comment by bensonfx** [comment]
有个组织，在国外找个vps，建个论坛。比现在一有情况，连讨论的地方都没有，而且目标小点。

**Comment by bensonfx** [comment]
![image](https://user-images.githubusercontent.com/3302960/31046424-a2644fd6-a62a-11e7-8d20-027529ccfd4c.png)

**Comment by fei5seven** [comment]
知道最近风头又紧了，用的一个SS供应商的域名都炸了，回头一看社长果然又匿了。老规矩，十九大低头行事，一切以十九大为主【笑】

**Comment by dou4cc** [comment]
@fei5seven 你这话说的我是不是也该匿掉~

**Comment by fei5seven** [comment]
@dou4cc 没必要啊，只是如同之前那个药丸转发一样，上网更困难一点，一般而言国家大事期间不会弄出来难听的新闻的，安啦

**Comment by dou4cc** [comment]
@xxnet 你把自己改成public member吧，[别指望phuslu回来继续开发了](https://github.com/goproxy0/goproxy/issues/2#issuecomment-333450695)。

**Comment by dou4cc** [comment]
@SeaHOH @jasonliul @candy2107 @johnsonz @Kisesy @fei5seven @blob2015 @Asteroids89 @qwerttaa @e2889e @ARwMq9b6 @MeABc @jzmswe @hyperdoit @lizongzeshunshun @Just2co @pgz123 @cxjava @jostyee @overajog @codexss @alsotang @renzhn @cyfdecyf @Akkariiin 项目已转给xxnet，删帖风险不再，请你们回来！

**Comment by codexss** [comment]
Goproxy特征太明显，现在的状况就算是维护也没法用了，换[Shadowsocks](https://github.com/shadowsocks)吧。

**Comment by dou4cc** [comment]
@codexss 我没把gop当主力，但请你回答这个问题：https://github.com/goproxy0/goproxy/issues/8

**Comment by xxnet** [comment]
​我对go 没有研究，担当不起维护大任，挂个名可以。
大家推荐几个能够继续维护的，可以拉入管理权限，负责review、发布新版。

至于项目前途，感觉只要大家在这里讨论交流，就有存在的意义。

**Comment by dou4cc** [comment]
@xxnet 我已经把自己踢出goproxy0了，请把readme.md的那行警示去掉。我艾特一堆人，都不理我也不知为啥~

**Comment by hyperdoit** [comment]
如果大家有心维护，就请新注册账号，匿名开发吧，要记住不要像P大，cloud大，break大，以史为鉴。
另，有人fork了r1623/r1624版本的源码吗？

**Comment by dou4cc** [comment]
是clowwindy，不是cloud。。这个仓库的code和release都是最新的。。

**Comment by fei5seven** [comment]
社长偷偷回来fork了一个项目，15小时前，看样子人是没事

**Comment by xxnet** [comment]
人​没事就好。

大家多参与，phuslu 压力就会少一点。
