### ISSUE TITLE
项目转移

### ISSUE THREAD

**Issue by dou4cc** [goproxy0/goproxy#6]
@xxnet 请求已发出，请确认。

--------
readme的url已改成相对地址。社长的自动编译发布脚本感觉很复杂的样子，就没管。

**Comment by xxnet** [comment]
不急，一般开完会就会回来的。

golang 我也不熟啊

**Comment by IntTMCT** [comment]
考虑接手维护吗

**Comment by dou4cc** [comment]
@IntTMCT 我不会go。

@xxnet 你考虑一下我的安危。你是匿名的，我是实名的。

**Comment by xxnet** [comment]
​好吧，大家都注意匿名，把之前的名字放一边，重新注册一个，不要和现实项目相关连。

**Comment by xxnet** [comment]
​未看到通知，你把这删了吧，我重新clone一个

https://github.com/XX-net/goproxy

**Comment by dou4cc** [comment]
@xxnet 重新发送了请求。
（你那边没releases也没已有的这几个issues，还是transfer一下吧

**Comment by dou4cc** [comment]
@xxnet 请接受成为goproxy0 owner的邀请。

**Comment by xxnet** [comment]
没有收到邮件通知，也没有在github上看到通知，不知如何接收。

**Comment by xxnet** [comment]
​收到了，已经加入
